# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f4df8ecedc316d39099490f73bd37678945e4b6d0ff67cb48a21ee57858563f94776231903de1be398a4349b3218255c58edeeafdd3f57d3e8a53ba5a7e67b5

test:
  secret_key_base: c0b97b3d39c50382124e0a8e5a10b33c1cc2e68b68dceb63493534e6f43cf8609216e0ce4a78711bd671db5a8517fbbfbaf917440d1271180ec0dd7046fa46df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
